Repository TeamPu/TeamPu-Server, pull requests merged in 2024-11, with the labels that each got.

#13 공통 응답 모델 구현
  src/main/java/com/kyonggi/teampu/global/response/ApiResponse.java
Labels: ✨ Feature

#17 공통 응답 모델 body 필드 타입 수정
  src/main/java/com/kyonggi/teampu/global/response/ApiResponse.java
Labels: 🔨 Refactor

#22 메인페이지 구현
  src/main/java/com/kyonggi/teampu/domain/mainPage/controller/MainPageController.java
  src/main/java/com/kyonggi/teampu/domain/mainPage/dto/MainPageResponse.java
  src/main/java/com/kyonggi/teampu/domain/mainPage/repository/MainPageRepository.java
  src/main/java/com/kyonggi/teampu/domain/mainPage/service/MainPageService.java
Labels: ✨ Feature

#28 (관리자 메인페이지) 야간 잔류 신청 조회 기능
  .gitignore
  src/main/java/com/kyonggi/teampu/domain/admin/controller/AdminController.java
  src/main/java/com/kyonggi/teampu/domain/admin/dto/response/AppliedInfoResponse.java
  src/main/java/com/kyonggi/teampu/domain/admin/service/AdminService.java
  src/main/java/com/kyonggi/teampu/domain/application/repository/ApplicationRepository.java
  src/main/java/com/kyonggi/teampu/domain/member/repository/MemberRepository.java
  src/main/resources/db/Add_Application.sql
  src/main/resources/db/Add_Member.sql
Labels: ✨ Feature

#26 야간잔류 신청 기능 구현
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/domain/Application.java
  src/main/java/com/kyonggi/teampu/domain/application/domain/ApplicationStatus.java
  src/main/java/com/kyonggi/teampu/domain/application/dto/ApplicationRequest.java
  src/main/java/com/kyonggi/teampu/domain/application/repository/ApplicationRepository.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
  src/main/java/com/kyonggi/teampu/domain/member/domain/CoParticipant.java
  src/main/java/com/kyonggi/teampu/domain/member/dto/CoParticipantRequest.java
  src/main/java/com/kyonggi/teampu/domain/member/dto/MemberInfoResponse.java
  src/main/java/com/kyonggi/teampu/domain/member/repository/MemberRepository.java
  src/main/java/com/kyonggi/teampu/global/response/ApiResponse.java
Labels: ✨ Feature

#35 야간잔류 삭제 기능 구현
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
Labels: ✨ Feature

#37 야간잔류 상세 조회 기능 구현
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/domain/Application.java
  src/main/java/com/kyonggi/teampu/domain/application/dto/ApplicationResponse.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
Labels: ✨ Feature

#39 야간잔류 수정 기능 구현
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
Labels: ✨ Feature

#32 메인 페이지 및 마이 페이지 관련 기능 디렉토리 이동
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/dto/MainPageResponse.java
  src/main/java/com/kyonggi/teampu/domain/application/repository/ApplicationRepository.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
  src/main/java/com/kyonggi/teampu/domain/mainPage/controller/MainPageController.java
  src/main/java/com/kyonggi/teampu/domain/mainPage/repository/MainPageRepository.java
  src/main/java/com/kyonggi/teampu/domain/mainPage/service/MainPageService.java
  src/main/java/com/kyonggi/teampu/domain/member/controller/MemberController.java
  src/main/java/com/kyonggi/teampu/domain/member/dto/MyPageRequest.java
  src/main/java/com/kyonggi/teampu/domain/member/dto/MyPageResponse.java
  src/main/java/com/kyonggi/teampu/domain/member/service/MemberService.java
  src/main/java/com/kyonggi/teampu/domain/myPage/controller/MyPageController.java
  src/main/java/com/kyonggi/teampu/domain/myPage/service/MyPageService.java
Labels: 🔨 Refactor

#40 (관리자) 야간 잔류 신청 승민 및 거부
  src/main/java/com/kyonggi/teampu/domain/admin/controller/AdminController.java
  src/main/java/com/kyonggi/teampu/domain/admin/dto/request/ApproveRequest.java
  src/main/java/com/kyonggi/teampu/domain/admin/service/AdminService.java
  src/main/java/com/kyonggi/teampu/domain/application/domain/Application.java
  src/main/java/com/kyonggi/teampu/global/exception/ErrorCode.java
  src/main/resources/db/Add_Member.sql
Labels: ✨ Feature

#42 불필요한 필드 삭제 및 start_time, end_time 기능 수정
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/domain/Application.java
  src/main/java/com/kyonggi/teampu/domain/application/dto/ApplicationRequest.java
  src/main/java/com/kyonggi/teampu/domain/application/dto/ApplicationResponse.java
  src/main/java/com/kyonggi/teampu/domain/application/repository/ApplicationRepository.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
Labels: 🐞 BugFix, 🔨 Refactor

#44 유닛 테스트 작성
  build.gradle
  src/main/java/com/kyonggi/teampu/domain/application/controller/ApplicationController.java
  src/main/java/com/kyonggi/teampu/domain/application/service/ApplicationService.java
  src/main/java/com/kyonggi/teampu/domain/member/dto/JoinRequest.java
  src/main/java/com/kyonggi/teampu/domain/member/dto/MyPageRequest.java
  src/main/java/com/kyonggi/teampu/domain/member/repository/MemberRepository.java
  src/main/java/com/kyonggi/teampu/domain/member/service/MemberService.java
  src/main/java/com/kyonggi/teampu/global/exception/ErrorCode.java
  src/test/java/com/kyonggi/teampu/domain/application/service/ApplicationServiceTest.java
  src/test/java/com/kyonggi/teampu/domain/member/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: ✅ Test, 📦 Chore

#47 deploy github action 스크립트 작성, dev_CI 스크립트 빌드 커맨드 수정, application.yml 파일 수정
  .github/workflows/deploy.yml
  .github/workflows/dev_CI.yml
  Dockerfile
  manifest/spring-redis.yml
  src/main/resources/application.yml
Labels: ✅ Test, 🔨 Refactor, 🌐 Infra
