Repository TeamPu/TeamPu-Server, pull requests merged in 2024-12, with the labels that each got.

#55 deploy yml파일 confilct fix
  .github/workflows/deploy.yml
  build.gradle
  src/main/resources/application.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra

#65 Docker 배포 환경의 Flyway 설정 및 테스트 환경 수정
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  Dockerfile
  src/test/java/com/kyonggi/teampu/TeamPuApplicationTests.java
  src/test/java/com/kyonggi/teampu/domain/application/service/ApplicationServiceTest.java
  src/test/java/com/kyonggi/teampu/domain/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: 🐞 BugFix, ✨ Feature, 🌏 Deploy, 🌐 Infra

#71 배포 시 Run Database Migration 에러 수정
  .github/workflows/test.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🗃 Database

#72 Run Database Migration에서 gradle 버전 명시
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🗃 Database

#74 fix: DB_HOST로 수정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix

#75 Update deploy.yml
  .github/workflows/deploy.yml
Labels: 🐞 BugFix

#76 Flyway 마이그레이션 실행하는 Gradle 명령어 추가
  .github/workflows/deploy.yml
  src/main/resources/application-cd.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database

#79 원격 배포(CD) 과정의 Gradle 빌드 과정에서의 의존성 문제 관련
  .github/workflows/deploy.yml
  build.gradle
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database

#80 flyway 설정 순서 변경
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database

#82 Gradle JVM 버전 설정 변경
  build.gradle
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database

#83 경고 메시지의 상세 수준을 제어하는 설정 추가
  gradle/wrapper/gradle-wrapper.properties
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database

#84 Gradle의 build 태스크 실행 명령어 추가
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database, 📦 Chore

#87 build.gradle에 Flyway 플러그인 추가
  build.gradle
Labels: 🐞 BugFix, 🌐 Infra, 📦 Chore

#88 Flyway 데이터베이스 연결 설정 수정
  .github/workflows/deploy.yml
  src/main/resources/application-cd.yml
Labels: 🐞 BugFix, 🌐 Infra, 🗃 Database

#89 docker 실행 후 db 연결
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌐 Infra, 🗃 Database, 🐋 Docker

#90 Flyway 데이터베이스 마이그레이션 설정 추가
  build.gradle
Labels: 🐞 BugFix, 🌏 Deploy, 🌐 Infra, 🗃 Database, 📦 Chore
